export * from "./HomeInnlab/home_innlab"
export * from "./InnlabForm/innlab-form"
export * from "./DatosPrueba/datos_prueba"
export * from "./DownloadPage/DownloadPage"
export * from "./UploadPage/UploadPage"
export * from "./AreasForm/areas_form"
